config/routes.rb
Rails.application.routes.draw do
  resources :candidate_profile, only: [:new, :create]

  devise_for :users

  namespace :admin do
    resources :candidate_profiles, only: [:index, :show]
    root 'candidate_profiles#index'
  end

  get '/guides' => 'guides#index'
  root 'home#index'
end

app/models/candidate_profile.rb
class CandidateProfile < ActiveRecord::Base
  validates :name, :email, :phone, :city, :age,
            :activity, :studies, :motivation,
            :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/candidate_profiles_controller.rb
class Admin::CandidateProfilesController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'

  def index
    @candidate_profiles = CandidateProfile.order(created_at: :desc)
  end

  def show
    @candidate_profile = CandidateProfile.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/candidate_profile_controller.rb
class CandidateProfileController < ApplicationController
  def create
    p params
    @profile = CandidateProfile.new(candidate_params)
    if @profile.save
      CandidateMailer.report_new_candidate_email(@profile).deliver_now
      render :post_submit
    else
      flash[:notice] = "Nu toate campurile obligatorii sunt completate"
      redirect_to new_candidate_profile_path
    end
  end

  def new
    @candidate = CandidateProfile.new
  end

  private

  def candidate_params
    params.require(:candidate_profile).permit!
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController 
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/candidate_profiles/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="panel panel-default">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th><th>Email</th><th>Phone</th><th>Application Date</th>
          </tr>
        </thead>
        <tbody>
          <% @candidate_profiles.each do |candidate| %>
            <tr>
              <td><%= link_to candidate.name, [:admin, candidate] %></td>
              <td><%= candidate.email %></td>
              <td><%= candidate.phone %></td>
              <td><%= candidate.created_at.to_formatted_s(:long) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/candidate_profiles/show.html.erb
<!-- email phone city activity studies age -->

<!-- motivation voluntariat
      project_idea
      teamwork
      last_skill
      agreement
      disagreement_comment -->

<div class="row">
  <div class="col-xs-12">
    <h2><%= @candidate_profile.name %></h2>
    <hr/>
  </div>
</div>

<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">
    <div class="panel panel-default">
      <table class="table table-striped">
        <tbody>
          <% %w(email phone city activity studies age).each do |item| %>
            <tr>
              <td><%= item.titleize %></td>
              <td><%= @candidate_profile.public_send(item) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-xs-12"><hr/></div>
</div>

<div class="row">
  <% %w(motivation
        voluntariat
        teamwork
        last_skill).each do |item| %>

    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading"><%= item.titleize %></div>
        <div class="panel-body">
          <p><%= @candidate_profile.public_send(item) %></p>
        </div>
      </div>
    </div>
  <% end %>

  <div class="col-md-4 col-sm-6 col-xs-12">
    <% agreement = @candidate_profile.agreement %>
    <div class="panel panel-default">
      <div class="panel-heading">Commitment: <b><%= agreement %></b></div>
      <% if agreement == "Nu" %>
        <div class="panel-body">
          <p><%= @candidate_profile.disagreement_comment %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/candidate_profile/new.html.erb
<section class="sec-form" style="padding-top: 60px;">
  <h2>Formular de aplicare</h2>
  <%= form_for @candidate, url: {action: "create"} do |f| %>
    <%= f.text_field :name, class: "sec-form-input label-tag", placeholder: "Numele și Prenumele"%>

    <%= f.text_field :email, class: "sec-form-input label-tag", placeholder: "E-mail" %>

    <%= f.text_field :phone, class: "sec-form-input label-tag", placeholder: "Numărul de telefon" %>

    <%= f.text_field :city, class: "sec-form-input label-tag", placeholder: "Localitatea în care te afli în prezent" %>

    <%= f.number_field :age, class: "sec-form-input label-tag", placeholder: "Ce vârstă ai?"%>

    <div class="sec-form-textarea">
      <%= f.label :activity do %>
        <p class="label-tag-with-info">Activitatea principală</p>
        <p class="info-label-tag">Ești elevă, studentă, deja angajată sau... spirit liber?</p>
      <% end %>
      <%= f.text_field :activity, class: "sec-form-input" %>
    </div>

    <%= f.text_field :studies, class: "sec-form-input label-tag", placeholder: "Domeniul în care activezi sau în care îți faci studiile" %>

    <div class="sec-form-textarea">
      <%= f.label :motivation do %>
        <p class="label-tag-with-info">Ce te motivează să aplici la acest curs?</p>
        <p class="info-label-tag">Descrie în ce mod cunoștințele obținute vor fi relevante pentru activitatea ta ulterioară.</p>
      <% end %>
      <%= f.text_area :motivation %>
    </div>

    <div class="sec-form-textarea">
      <%= f.label :voluntariat do %>
        <p class="label-tag-with-info">Ai activități de voluntariat?</p>
        <p class="info-label-tag">Unul din obiectivele cursului e de a te ajuta să dezvolți competențe tehnice care îți vor permite să dezvolți soluții pentru probleme sociale din domeniul tău de activitate sau voluntariat.</p>
      <% end %>
      <%= f.text_area :voluntariat %>
    </div>

    <!-- <div class="sec-form-textarea">
      <%#= f.label :project_idea do %>
        <p class="label-tag-with-info">Ai o idee clară de proiect, care se încadrează în descrierea pe care am dat-o noi și pe care o vei implementa în timpul cursului?</p>
        <p class="info-label-tag">Te rugăm să descrii cu maximum de detalii ce anume îți propui să realizezi.</p>
      <%# end %>
      <%#= f.text_area :project_idea %>
    </div> -->

    <div class="sec-form-textarea">
      <p class="label-tag"><%= f.label :teamwork, "Ai experiență de lucru în echipă? Te rugăm să o descrii mai jos." %></p>
      <%= f.text_area :teamwork %>
    </div>

    <div class="sec-form-textarea">
      <%= f.label :last_skill do %>
        <p class="label-tag-with-info">Cum îți autoevaluezi capacitatea de a învăța în autonomie?</p>
        <p class="info-label-tag">Care a fost ultima problemă tehnică cu care te-ai confruntat și cum ai rezolvat-o? Care este ultimul lucru pe care l-ai învățat singură și care au fost resursele pe care le-ai folosit?</p>
      <% end %>
      <%= f.text_area :last_skill %>
    </div>

    <div>
      <%= f.label :agreement do %>
        <p class="label-tag-with-info">Prin aplicarea la acest curs, îți asumi responsabilitatea de a-l urma în integralitate.</p>
        <p class="info-label-tag">Noi am investit mult timp și efort în organizarea acestui curs, contăm pe seriozitatea și angajamentul participanților. Dacă există motive din care nu vei putea participa la anumite părți din curs, te rugăm să le enunți mai jos.</p>
      <% end %>
      <div class="sec-form-radio">
        <label>
          <%= f.radio_button :agreement, "Da", class: "radio-input" %>Voi participa la toate activitățile cursului
        </label>
        <label>
          <%= f.radio_button :agreement, "Nu", class: "radio-input" %>Nu pot frecventa toate activitățile
        </label>
      </div>
      <div id="agreement_comment" style="display: none;">
          <%= f.text_field :disagreement_comment, class: "sec-form-input why-input ", placeholder: "De ce?" %>
      </div>
    </div>

    <div class="sec-form-submit">
      <%= f.submit "Trimite", class: "btn btn-submit" %>
    </div>
  <% end %>
</section>
<script>
$("#candidate_profile_agreement_nu").click(function() {
  $("#agreement_comment").show();
});
$("#candidate_profile_agreement_da").click(function() {
  $("#agreement_comment").hide();
});

jQuery.extend(jQuery.validator.messages, {
    required: "Completează acest câmp",
    // remote: "Please fix this field.",
    email: "Formatul acestui email este invalid",
    // url: "Please enter a valid URL.",
    // date: "Please enter a valid date.",
    // dateISO: "Please enter a valid date (ISO).",
    // number: "Please enter a valid number.",
    // digits: "Please enter only digits.",
    // creditcard: "Please enter a valid credit card number.",
    // equalTo: "Please enter the same value again.",
    // accept: "Please enter a value with a valid extension.",
    // maxlength: jQuery.validator.format("Please enter no more than {0} characters."),
    // minlength: jQuery.validator.format("Please enter at least {0} characters."),
    // rangelength: jQuery.validator.format("Please enter a value between {0} and {1} characters long."),
    // range: jQuery.validator.format("Please enter a value between {0} and {1}."),
    // max: jQuery.validator.format("Please enter a value less than or equal to {0}."),
    // min: jQuery.validator.format("Please enter a value greater than or equal to {0}.")
});

$(function() {
  $("#new_candidate_profile").validate({

    rules: {
      "candidate_profile[name]": "required",
      "candidate_profile[email]": {
        required: true,
        email: true
      },
      "candidate_profile[phone]": "required",
      "candidate_profile[city]": "required",
      "candidate_profile[age]": "required",
      "candidate_profile[activity]": "required",
      "candidate_profile[studies]": "required",
      "candidate_profile[motivation]": "required",
    },

    submitHandler: function(form) {
      form.submit();
    },
    errorPlacement: function(error, element) {
      if (element.parent().is("div")) {
        element = element.parent();
      }
      var new_error = $('<div class="custom-error"></div>').append(error);
      element.after(new_error);
    },
    success: function(element){
      element.parent().remove();
    }
  });
});
</script>
<style>
.label-tag-with-info {
  font-family: "Titillium Web";
  border: 0 !important;
  padding-top: 4px !important;
  font-size: 16px !important;
}
.label-tag {
  font-family: "Titillium Web";
  font-size: 16px !important;
}
.info-label-tag {
  font-family: "Titillium Web";
  color: #A5A5A5 !important;
  font-size: 14px !important;
}
.why-input {
  margin-top: 6px;
}
.radio-input {
  margin-right: 10px;
}
.custom-error {
  margin-top: -12px;
  margin-bottom: 11px;
  font-size: 14px;
  font-family: "Titillium Web";
  padding-left: 10px;
  color: #EB524F;
}
</style>

app/views/candidate_profile/post_submit.html.erb
<div id="fb-root"></div>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  $(document).ready(function() {
    $.ajaxSetup({ cache: true });
    $.getScript('//connect.facebook.net/en_US/sdk.js', function(){
      FB.init({
        appId: '{your-app-id}',
        version: 'v2.3' // or v2.0, v2.1, v2.0
      });
      $('#loginbutton,#feedbutton').removeAttr('disabled');
      FB.getLoginStatus(updateStatusCallback);
    });
  });
</script>

<div class="response-part">
  <p style="font-size: 25px;">Aplicarea dumnevoastră a fost trimisă cu succes</p>
  <p style="margin-top: 20px; font-size: 20px;">Pentru a urmări noutățile, dați un like paginei noastre de eveniment</p>

  <br />
  <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="150" data-layout="button" data-action="like" data-show-faces="false" data-share="false"></div>
</div>

<style>
.response-part {
  margin-top: 200px;
  text-align: center;
  font-family: "Titillium Web";
}
</style>

app/views/guides/index.html.erb
<section class="sec-sponsors" id="Guides">
  <h3>Ghid</h3>
  <p>
    Documentul-ghid se află aici: <a href="http://bit.ly/1EMP3mj">google doc</a>
  </p>
  <br/>
  <p>
    Vă urăm succes :)
  </p>
</section>

app/views/home/index.html.erb
<section class="sec-header" id="RailsGirls">
  <div class="sec-header-logo">
    <%= image_tag 'logo_red.png', alt: 'RailsGrils Chisinau' %>
  </div>
  <div class="sec-header-period">
    <p><strong>Editia II</strong></p>
    <p>31 Ianuarie - 21 Februarie 2016</p>
    <%= link_to "Aplicarea a luat sfârșit :(", "#", class: "btn btn-apply"%>
  </div>
</section>

<section class="sec-about mini-slide" id="Despre" style="font-family: 'Titillium Web';">
  <ul>
    <li class="calendar active">Durată</li>
    <li class="reason">Proiecte</li>
    <li class="why">De ce să particip?</li>
    <li class="money">Cost</li>
    <li class="mentors">Mentori</li>
    <li class="who">Cine poate participa?</li>
  </ul>

  <select>
    <option selected="selected">Durată</option>
    <option>Proiecte</option>
    <option>De ce să particip?</option>
    <option>Cost</option>
    <option>Mentori</option>
    <option>Cine poate participa?</option>
  </select>

  <div class="sec-about-text">
    <p>Cursurile vor fi lansate la ceremonia de deschidere pe 31 ianuarie, iar activitățile didactice vor avea loc în sâmbetele de 6, 13 și 20 februarie 2016. Duminică, 21 februarie, te invităm la lansarea proiectelor dezvoltate în timpul atelierelor.</p>
    <br />
    <p>În total, vei beneficia de 36 de ore de curs și ateliere practice, pe care te încurajăm să le suplimentezi cu lucru independent pe parcursul săptămânii.</p>
    <br />
    <p>La sfârșitul cursului, ne propunem să creăm o comunitate activă, alături de care vom organiza alte evenimente și ateliere.</p>
    <br />
    <br />
    <h4><strong>PROGRAM:</strong></h4>
    <br />
    <p><strong>Joi, 21 ianuarie</strong> - Se închide perioada de aplicare. Așa că grăbiți-vă ;)</p>
    <br />
    <p><strong>21-24 ianuarie</strong> - Anunțăm participanții admiși, răspundem la întrebările voastre, iar voi - la ale noastre.</p>
    <br />
    <p>
      <strong>Duminică, 31 ianuarie - 13:00 - 17:00</strong> - Generator Hub
      Deschiderea cursului. Vom prezenta scopul cursului, forma grupurile de lucru, da toate sfaturile pe care putem să le dăm în patru ore și instala software-ul necesar pentru cei care vor să lucreze cu propriul laptop.
    </p>
    <br />
    <p>
      <strong>Sâmbătă, 6, 13 și 20 februarie - 10:00 - 19:00</strong> - Centrul de Informare și Acces
      Cursurile propriu-zise. Stăm, scriem cod, discutăm, mai privim o prezentare și facem gimnastică.
    </p>
    <br />
    <p>
      <strong>Duminică, 21 februarie - 17:00 - până-n zori</strong> - Generator Hub
      Închiderea cursului. Ne lăudăm cu ce-am făcut, discutăm, mai avem vreo două prezentări și vedem ce posibilități de follow-up există.
    </p>
  </div>

  <div class="sec-about-text">
    <p>Iată câteva proiecte pe care le propunem spre implementare participanților:<p>

    <br/>
    <p>Social:</p>
    <ul class="info-ul with-bullets">
      <li>Managementul cazurilor pentru asistenții sociali: un serviciu care permite asistenților sociali să posteze informații și actualizări despre persoanele care beneficiază de serviciile de asistență socială</li>
      <li>Sistem de sistematizare a informațiilor despre pacienți: o platformă web în care lucrătorii medicali pot actualiza informații despre starea și tratamentul pacienților pe care îi tratează</li>
      <li>Transparența declarațiilor și afiliațiilor politice: o platformă web pe care jurnaliștii pot întreține profilul public al oamenilor politici din Moldova - apartenența la partide și blocuri politice, declarații și gradul de împlinire a promisiunilor, voturi și absențele de la ședințe</li>
      <li>Transparența proiectelor care au primit investiții din străinătate: un serviciu public în care vor fi agregate datele și rapoartele despre proiectele finanțate de Uniunea Europeană în Republica Moldova: condițiile, cheltuielile, actorii și gradul de completare a proiectelor de dezvoltare în infrastructură, educație și sănătate</li>
    </ul>

    <br/>
    <p>Hobby și cotidian:</p>
    <ul class="info-ul with-bullets">
      <li>Prețuri și reduceri: o platformă web pe care utilizatorii pot posta informații despre prețurile la produse și servicii, anunța reduceri și oferte, precum și publica evaluări pentru prestatorii de bunuri și servicii din Republica Moldova</li>
      <li>Călătorii: un serviciu în care călătorii Moldoveni pot publica informații despre călătoriile spre diferite destinații: restricțiile de viză, liniile aeriene, costul vieții, cazare, transport și securitate</li>
      <li>Fotografii vechi, memorii și istorii: o platformă pe care utilizatorii pot posta fotografii vechi de familie, cu istorioare și notițe despre evenimentele sau oamenii de pe fotografii</li>
    </ul>
  </div>

  <div class="sec-about-text">
    <p>Vom învăța împreună ce este o aplicație web și te vom ajuta să realizezi propriul proiect folosind Ruby on Rails, tehnologia care înregistrează în prezent cea mai mare creștere în popularitate printre programatorii web din Republica Moldova. Vei descoperi practicile și tehnologiile moderne în contexte actuale.</p>
    <br />
    <p>De la începător la propriul proiect? Noi credem că e posibil.</p>
    <br />
    <p>Alături de noi și colaborând cu ceilalți participanți vei învăța:</p>
    <ul class="info-ul">
      <li>Ce este o aplicație web și ce se află în spatele aplicațiilor moderne</li>
      <li>Ce înseamnă web development, protocolul HTTP, conexiuni server-client</li>
      <li>Cum este creată o pagină web statică: HTML și CSS</li>
      <li>Cum este creat conținutul dinamic: Ruby și Ruby on Rails</li>
      <li>Cum să lucrezi în echipă și să găsești soluții pentru problemele tehnice cu care te confrunți</li>
    </ul>
    <br />
    <p>Vom încerca să demistificăm concepte ce par acum complexe și vom acoperi, pas cu pas, ceea ce este necesar pentru a dezvolta funcționalitatea unei mici retele sociale.</p>
  </div>

  <div class="sec-about-text">
    <p>Costul? Simplu! Absolut gratuit. Cerem de la tine doar asiduitate și sete de cunoaștere.</p>
  </div>

  <div class="sec-about-text">
    <p>Atelierele vor fi ghidate de unii dintre cei mai buni programatori Ruby on Rails din Republica Moldova, precum și alți specialiști din domeniul IT, care îți vor pune la dispoziție vastele lor cunoștințe și experiență.</p>
    <br />
    <ul class="info-ul">
      <li>Alisa Frunză - Participant la RailsGirls Ediția I, programator Ruby on Rails</li>
      <li>Andrei Căpăstru - Student, Universitatea Tehnică a Moldovei</li>
      <li>Andrei Istratii - Student, Universitatea Tehnică a Moldovei</li>
      <li>Boris Gherman - Programator Front-End, Freelancer</li>
      <li>Diana Mihuță - Participant la RailsGirls Ediția I</li>
      <li>Doina Leca - Director Executiv, Blogant</li>
      <li>Ivan Danci - Programator Ruby on Rails, Fusion Works</li>
      <li>Ivan Zarea - Programator Ruby on Rails, profesor la Universitatea Tehnică a Moldovei</li>
      <li>Marina Cucer - Consultant Resurse Umane, Pentalog</li>
      <li>Mihai Coșleț - Student, Universitatea Tehnică a Moldovei</li>
      <li>Olga Batîr - Administrator, Generator Hub</li>
      <li>Sergiu Terman - Programator Ruby on Rails, Blogant</li>
      <li>Tatiana Moldovan - Programator Scala, Endava</li>
      <li>Vladimir Pintea - Programator Ruby on Rails, Fusion Works</li>
      <li>Vladislav Ledniov - Programator Ruby on Rails, Fusion Works</li>
    </ul>
  </div>

  <div class="sec-about-text">
    <p>Tinere între 18 și 28 de ani (facem, desigur, excepții), care vor să descopere ce este o aplicație web și să realizeze propriul proiect. Încurajăm începătorii, vino chiar dacă nu ai lucrat niciodată la dezvoltarea unui produs web. Cunoașterea limbii engleze te va avantaja în timpul activităților individuale.</p>
    <br />
    <p>Experiența anterioară în proiecte sociale și ideea unui proiect pe care îl vei implementa în timpul atelierelor este binevenită - noi vrem să te încurajăm să dezvolți un instrument util ție și comunității.</p>
  </div>
</section>

<section class="sec-apply" id="Aplica">
  <ul class="sec-apply-list">
    <li class="form"><i></i><span>1.</span> Completează formularul de aplicare</li>
    <li class="interview"><i></i><span>2.</span> Participă la interviu online</li>
    <li class="acceptance"><i></i><span>3.</span> Confirmă participarea la eveniment </li>
  </ul>

  <div class="sec-apply-btn">
    <%= link_to "Aplicarea a luat sfârșit :(", "#", class: "btn btn-apply"%>
  </div>
</section>

<section class="sec-contact" id="Contact">
  <h3>Pentru a ne adresa orice întrebare, te rugăm să ne contactezi</h3>
  <div class="sec-contact-info">
      <p class="mail"><i></i><a href="mailto:railsgirlsmd@gmail.com">railsgirlsmd@gmail.com</a></p>
      <p class="phone"><i></i>+373 79111321</p>
  </div>
</section>

<section class="sec-sponsors" id="Sponsors">
  <h3>Parteneri</h3>
  <div class="sponsors-logo">
    <a href="http://www.itacces.md/index.php?l=ro">
      <%= image_tag 'sponsor1.jpg', alt: 'Centrul de Informare și Acces', width: 200 %>
    </a>

    <a href="http://hub.md/">
      <%= image_tag 'sponsor3.png', alt: 'Generator Hub', width: 100 %>
    </a>

    <a href="http://fusionworks.md/">
      <%= image_tag 'sponsor7.png', alt: 'FusionWorks', width: 150 %>
    </a>
  </div>
  <div class="sponsors-logo">
    <a href="http://granat.md/">
      <%= image_tag 'sponsor2.png', alt: 'Granat', style: 'margin-left: 65px;margin-top: 20px;' %>
    </a>

    <a href="http://www.endava.com/">
      <%= image_tag 'sponsor10.jpg', alt: 'Endava Moldova', width: 200, style: "margin-top: 40px;" %>
    </a>

    <a href="http://www.cuptorulculemne.md/">
      <%= image_tag 'sponsor8.png', alt: 'Corso Pizza', style: 'margin-left: 65px; margin-top: 20px;' %>
    </a>
  </div>

  <div class="sponsors-logo">

    <a href="https://blogant.net">
      <%= image_tag 'sponsor12.svg', alt: 'Blogant', width: 150%>
    </a>

    <a href="http://molddata.md/">
      <%= image_tag 'sponsor11.png', alt: 'Molddata', width: 200%>
    </a>
    
    <a href="http://www.codefactorygroup.com/">
      <%= image_tag 'sponsor4.png', alt: 'CodeFactory', width: 200, style: "padding-top: 40px;margin-bottom: -40px;"%>
    </a>

  </div>
</section>
<style>
.info-ul li {
  display: list-item;
  text-transform: none;
  text-align: left;
  width: 100%;
  margin-top: 6px;
}

.with-bullets {
  list-style-position: outside;
  list-style-type: circle
}

.with-bullets li {
  margin-left: 30px;
  padding-left: 0px;
}
</style>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Administration</title>
  <%= stylesheet_link_tag    'admin', media: 'all' %>
  <%= javascript_include_tag 'admin' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Admin Panel</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Candidates", admin_candidate_profiles_path %></li>
          <li><%= link_to "Home Page", root_path %></li>
        </ul>

        <p class="navbar-btn navbar-right">
          <%= link_to "Log Out", destroy_user_session_path, :method => :delete, :class => "btn btn-default" %>
        </p>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>


  <div class="container">
    <% flash.each do |name, msg| -%>
      <div class="row">
        <div class="col-xs-12">
          <div class="alert alert-<%= name == :error ? "danger" : "info" %> alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <p><%= msg %></p>
          </div>
        </div>
      </div>
    <% end -%>

    <%= yield %>
  </div>
</body>
</html>